server:
  port: 0
spring:
  application:
    name: admin-server
eureka:
  client:
    service-url.defaultZone: http://localhost:9000/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1