server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    cache-refresh-executor-exponential-back-off-bound: 2
  instance:
    instance-id: reportability_01
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
management:
  security:
    enabled: false

spring:
  application:
    name: ReportabilityService
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:7005