server:
  port: 0

instanceId: ${random.int[0,1000]}
autoconfigured.eligibility.response: static_eligibility
eligibility.response: ${autoconfigured.eligibility.response}_${instanceId}
---
spring:
  profiles: instance-1
server:
  port: 8002
instanceId: 1
autoconfigured.eligibility.response: static_eligibility
eligibility.response: ${autoconfigured.eligibility.response}_${instanceId}
---
spring:
  profiles: instance-2
server:
  port: 8003
instanceId: 2
autoconfigured.eligibility.response: static_eligibility
eligibility.response: ${autoconfigured.eligibility.response}_${instanceId}
