instanceId: ${random.int[0,1000]}
autoconfigured.eligibility.response: static_eligibility

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: eligibility_${instanceId}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

eligibility.response: ${autoconfigured.eligibility.response}_${instanceId}
spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9700